config/routes.rb
Simpleplan::Application.routes.draw do
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  get "profile" => "users#edit", :as => "profile"

  resources :projects
  resources :sessions
  resources :users

  root :to => 'welcome#index'
end

app/models/company.rb
class Company < ActiveRecord::Base
  # attributes
  attr_accessible :name

  # associations
  has_many :users
  
  # validations
  validates_presence_of :name, :message => "required"
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  # attributes
  attr_accessible :name, :description, :active
  
  # associations
  
  # validations
  validates_presence_of :name
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # attributes
  attr_accessible :email, :password, :password_confirmation, :name, :timezone
  attr_accessor :password

  # associations
  belongs_to :company
  
  # callbacks
  before_save :encrypt_password
  
  # validations
  validates_presence_of :email, :message => "Sorry, a valid email is required."
  validates_uniqueness_of :email, :message => "Looks like that email is taken."
  
  validates_presence_of :password, :on => :create, :message => "Please enter a password."
  validates_confirmation_of :password, :message => "Oh no!  Confirmation doesn't match."
  validates_length_of :password, :within => 6..24
  
  # private methods
  private
  
  def self.authenticate(email, password)

    user = User.find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end    
  end
  
  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, salt)
    end
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :current_company
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def current_company
    @current_company ||= current_user.company if current_user
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html, :json, :xml
  
  def index
    @projects = Project.all
    respond_with @projects
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      flash[:info] = "Already logged in"
      redirect_to root_url
    end
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      flash[:success] = random_login_quote
      redirect_to root_url
    else
      flash.now[:error] = random_invalid_login_quote
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:warning] = random_logout_quote
    redirect_to root_url
  end
  
  
  private
  
  def random_login_quote
    quotes = ["Logged in successfully!", 
              "Awesome! Thanks for logging in.",
              "Welcome back, we missed you.",
              "Where have you been?",
              ":-)"]
    quotes[rand(quotes.size)]
  end
  
  def random_logout_quote
    quotes = ["Logged out successfully!", 
              "Sorry to see you go.  :-(",
              "Come back real soon!",
              "Leaving already?",
              "Don't worry.  We'll keep things running while you're gone.",
              "We understand.  You have more <strong>important</strong> things to do.".html_safe]
    quotes[rand(quotes.size)]
  end

  def random_invalid_login_quote
    quotes = ["<strong>Sorry</strong>, but that login was invalid.".html_safe, 
              "Hmmm.  Something is wrong with that login.",
              "Would you mind trying that again?",
              "It's OK. I'm sure you just typed that incorrectly.",
              "I'm sorry, Dave. I'm afraid I can't do that.",
              "Hey, don't worry.  But would you mind trying that again?"]
    quotes[rand(quotes.size)]
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if current_user
      flash[:info] = "Already logged in"
      render "add_new_user"
    else
      @user = User.new
    end
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = random_register_quote
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render "new"
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:success] = "Your profile was updated successfully."
      redirect_to profile_path
    else
      render "edit"
    end
  end


  def add_new_user
  end

  private
  
  def random_register_quote
    quotes = ["Welcome aboard!", 
              "<strong>WOW!</strong> Thanks for signing up!".html_safe,
              "We knew you couldn't resist!",
              "Thank you for signing up!",
              "<strong>Fantastic!</strong> You are now a member of an elite team of project planners.".html_safe]
    quotes[rand(quotes.size)]
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  
  def fluid()
    content_for(:fluid) { "-fluid" }
  end

  def title(title)
    content_for(:title) {title}
  end

  def funny_name
    names = ["John Rambo", 
             "Your full name",
             "Type your name here",
             "FirstName LastName",
             "Samus Aran",
             "Moe Howard",
             "Larry Fine",
             "Curly Howard",
             "Shemp Howard",
             "John Doe"]
    names[rand(names.size)]
  end


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def random_email_placeholder_text
    emails = ["somebody@example.com", 
              "me@example.com",
              "Your email here...",
              "seriousbusinessdude@example.com",
              "immapc@example.com",
              "immamac@example.com"]
    emails[rand(emails.size)]
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_alerts.html.erb
<center>
	<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, id:"flash_#{name}", class:"alert-message #{name}" %>
	<% end %>
</center>

app/views/layouts/_hero.html.erb
<div class="navbar navbar-fixed">
	<div class="navbar-inner">
		<div class="container">
			<% if params[:controller] != "welcome" %>
				<a class="brand" href="/">SimplePlan</a>
			<% end %>
			<p class="pull-right" style="margin-left:30px;"><%= link_to "Log In", login_path %></p>
			<p class="pull-right" style="margin-left:30px;"><%= link_to "Sign Up", signup_path %></p>
			<p class="pull-right" style="margin-left:30px;"><%= link_to "Blog", signup_path %></p>
			<p class="pull-right" style="margin-left:30px;"><%= link_to "Pricing", signup_path %></p>
			<p class="pull-right" style="margin-left:30px;"><%= link_to "Tour", signup_path %></p>
		</div>
	</div>
</div>
<div class="container hero-unit">
	<%= render "layouts/alerts" %>

	<% if params[:controller] == "welcome" %>
		<header class="jumbotron subhead" id="overview">
			<h1>SimplePlan</h1>
			<br />
			<p class="lead">Start planning your projecs the <strong>simple</strong> way.</p>
		</header><br /><br />

		<div class="row">
			<div class="span6">
	          <h2>Register</h2>
			  <p>Registration is fast, easy and free!</p>
	          <p><%= link_to "Sign up in less than 30 seconds...", signup_path, class:"btn primary large" %></p>
	        </div>
			<div class="span6">
	          <h2>Log in and start planning</h2>
			  <p>Aleady a member?</p>
	          <p><%= link_to "Yes, I want to log in...", login_path, class:"btn success large" %></p>
	        </div>
		</div>
	<% else %>
		<%= yield :splash_pages %>
	<% end %>
</div>

app/views/layouts/_sidebar.html.erb
<h3>Dashboard</h3>
<h3>Inbox</h3>
<h3>Calendar</h3>
<h3>My Tasks</h3>
<h3>My Projects</h3>

app/views/layouts/_toolbar.html.erb
<div class="topbar">
	<div class="topbar-inner">
		<div class="container-fluid">
			<a class="brand" href="/">SimplePlan</a>
			<ul class="nav">
				<li class="active"><%= link_to "Home", root_url %></li>
				<li><%= link_to "Projects", projects_path %></li>
			</ul>
			<p class="pull-right" style="margin-left:30px;">
				<%= link_to "Logout", logout_path %>
			</p>
			<p class="pull-right" style="margin-left:30px;">
				<%= link_to "My Account", profile_path, class:"strong" %>
			</p>
			<form class="pull-right" action="">
				<input type="text" class="span6" placeholder="Search" />
			</form>
		</div>
	</div>
</div>


<div class="navbar navbar-static">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "SimplePlan", root_url, class:'brand' %>
			<ul class="nav">
				<li class="active"><%= link_to "Home", root_url %></li>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= content_for?(:title) ? yield(:title) : "SimplePlan" %></title>
		<%= stylesheet_link_tag    "application" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		
		<style type="text/css">
		      /* Override some defaults */
			  <% if current_user %>
				  html, body { background-color: #F3EDE7; }
			  <% else %>
				  html, body { background-color: #222222; }
			  <% end %>
			  body { padding-top: 60px; }
		</style>

		<!-- Google Web Fonts -->
		<link href='http://fonts.googleapis.com/css?family=Acme' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<% if current_user %>
			<%= render "layouts/toolbar" %>
			<div class="container<%= content_for?(:fluid) ? yield(:fluid) : "" %>">
				<%= yield :left_sidebar %>
				<%= yield :right_sidebar %>
				<%= yield :content %>
			</div>
		<% else %>
			<%= render "layouts/hero" %>
		<% end %>
	</body>
</html>

app/views/projects/index.html.erb
<h1>Projects</h1>

app/views/users/add_new_user.html.erb
<% content_for :content do %>
	<div class="content">
		<%= render "layouts/alerts" %>
		<h2>Whoops!</h2>
		<br />
		<div class="alert-message block-message success">
			<p>
				<strong>Whoa there!</strong>
				It appears you want to register a new user but you are already logged in.
			</p>
			<p>
				Instead, you probably meant to add new members to your account.
			</p>
			<div class="alert-actions">
				<%= link_to "Yes, I want to add members to my account.", "#", class:'btn small' %>
				<%= link_to "No, this was a mistake.", root_url, class:'btn small' %>
			</div>
		</div>
	</div>
<% end %>

app/views/users/edit.html.erb
<% title "Edit Profile" %>

<% content_for :content do %>
	<div class="content">
		<%= render "layouts/alerts" %>
		<div class="page-header">
			<h1>My Profile</h1>
		</div>

		<div class="row">
			<div class="span10">
				<%= twitter_bootstrap_form_for @user do |user| %>
					<%= user.text_field :email %>

					<%= user.password_field :password do %>
						<span class="help-block">Type your new password here or leave blank to ignore.</span>
					<% end %>
		
					<%= user.password_field :password_confirmation, "Confirm", class:"large" do %>
					<% end %>

					<hr />
			
					<%= user.text_field :name, "Your name", autofocus:'autofocus', placeholder:funny_name %>
					<%= user.time_zone_select :timezone, "Time zone" %>

					<%= user.actions do %>
						<%= user.submit 'Update my account...' %>
						<%= link_to "Cancel", root_url, class:'btn' %>
					<% end %>
				<% end %>
			</div>
			<div class="span5">
			</div>
	</div>
<% end %>

app/views/users/new.html.erb
<% content_for :splash_pages do %>
	<div class="row">
		<div class="span8">
			<h2>Register with SimplePlan</h2>
			<br />
			<%= twitter_bootstrap_form_for @user do |user| %>
				<%= user.email_field :email, class:'xlarge span4', :placeholder => 'simpleplanlovesme@example.com', autofocus:'autofocus' %>
				<br />
				<%= user.password_field :password, class:'xlarge span4'  %>
				<br />
				<%= user.password_field :password_confirmation, class:'xlarge span4'  %>
				<fieldset class="form-actions">
					<%= user.submit 'Sign up and start planning!', class:'btn success' %>
					<%= link_to "Cancel", root_url, class:'btn' %>
				</fieldset>
			<% end %>
		</div>
		<div class="span4">
			<h3>Already a member?</h3>
			<br />
			<%= link_to "Log in!", login_path, class:'btn large info' %>
		</div>
	</div>
<% end %>

app/views/welcome/index.html.erb
<% title "Dashboard" %>
<% fluid %>
<% content_for :left_sidebar do %>
	<div class="sidebar left">
		<%= render "layouts/sidebar" %>
	</div>
<% end %>

<% content_for :content do %>
	<div class="content">
		<%= render "layouts/alerts" %>
		<% if current_user %>
			<h1>Dashboard</h1>
		<% end %>
	</div>
<% end %>